name: Sync Repository

on:
  # Trigger on push ke semua branch
  push:
    branches:
      - '**'
  # Trigger ketika ada tag baru
  create:
    tags:
      - '**'
  # Trigger ketika ada tag yang dihapus
  delete:
    tags:
      - '**'
  # Optional: Bisa ditrigger manual dari GitHub Actions tab
  workflow_dispatch:

# Memberikan permission read untuk GITHUB_TOKEN yang otomatis disediakan oleh GitHub Actions
permissions:
  contents: read

jobs:
  sync:
    # Mencegah workflow berjalan di repository tujuan
    if: github.repository != 'target-username/target-repo'
    runs-on: ubuntu-latest
    name: Sync Repository
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Diperlukan untuk mendapatkan semua history

      - name: Sync to Target Repository
        uses: rianllauo/github-actions-auto-push@main  # Sesuaikan dengan username dan branch Anda
        with:
          destination_repo: 'target-username/target-repo'  # Ganti dengan repo tujuan
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}  # Ini perlu ditambahkan di repository secrets
          target_branch: 'main'  # Optional, default ke 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Token ini otomatis disediakan oleh GitHub Actions, tidak perlu setup
