name: "Repository Sync Action"
description: "Automatically sync entire repository with another GitHub repository"
author: "rianllauo"

inputs:
  destination_repo:
    description: "Destination repository in format username/repository"
    required: true
  ssh_private_key:
    description: "SSH private key for repository authentication (should be stored in secrets)"
    required: true
  target_branch:
    description: "Branch to sync to (default: main)"
    required: false
    default: "main"
runs:
  using: "composite"
  steps:
    - run: |
        chmod +x ${{ github.action_path }}/entrypoint.sh
        ${{ github.action_path }}/entrypoint.sh \
          "${{ inputs.destination_repo }}" \
          "${{ inputs.target_branch }}" \
          "${{ inputs.ssh_private_key }}"
      shell: bash
