name: "Push to Another Repository"
description: "Push a specific folder to another GitHub repository"
author: "rianllauo"
inputs:
  source_directory:
    description: "Directory to push"
    required: true
  destination_repo:
    description: "Destination repository"
    required: true
  target_branch:
    description: "Branch to push to"
    required: true
  commit_message:
    description: "Commit message"
    required: true
  github_token:
    description: "GitHub token for authentication"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        chmod +x ${{ github.action_path }}/entrypoint.sh
        ${{ github.action_path }}/entrypoint.sh \
          "${{ inputs.source_directory }}" \
          "${{ inputs.destination_repo }}" \
          "${{ inputs.target_branch }}" \
          "${{ inputs.commit_message }}" \
          "${{ inputs.github_token }}"
      shell: bash
